version: '3.4'
services:
  apiseasonalmedic:
    image: ${DOCKER_REGISTRY-}apiseasonalmedic
    build:
      context: seasonalMedic
      dockerfile: Dockerfile
  SeasonalMedicDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SeasonalMedic.Db
    volumes:
      - ./.containers/database:/var/opt/msql/data
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SeasonalMedic123!"
